# Generated by Django 3.2.8 on 2022-10-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=15)),
                ('cep', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=5)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
