# Generated by Django 4.2.1 on 2023-05-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descricao',
            field=models.CharField(default='teste', max_length=200),
            preserve_default=False,
        ),
    ]
